// 通用拦截页（block page）特征库 —— 厂商硬签名之外的兜底识别层。
//
// 为什么要这一层（实战缺陷）：
//   WafIdentifier 原先只比对 wafRules.js 的 62 家厂商签名，「识别不出」被当成「不存在」。
//   但厂商签名本质是静态快照：国产云 WAF 拦截页按月改版、CDN 透传的自定义规则页、
//   自建 ModSecurity 被改写过的拒绝页，一律不在表内 → 漏识别。漏识别的代价不是「少一条提示」，
//   而是引擎继续用裸 payload 撞同一面墙（整轮请求全被拦 → 0 检出）。
//   本层只回答一个问题：「这个响应是不是一个拦截页」，不试图说出厂商名。
//
// 为什么判据必须保守（重要）：
//   误判「拦截页」的代价是发包形态被改（tamper 重跑 = 全站请求翻倍）。因此：
//   1) 状态码门槛：只有 status ∈ {403,406,418,429,503} 才允许「任一通用特征」触发；
//      其余状态码（302/400/500…）语义混杂，即使正文出现拦截字样也不判定——宁可不判也不猜。
//   2) status === 200 时必须命中「成对强特征」：拦截语义 + 处置语义同时出现才算
//      （如「含有攻击特征」+「已被…拦截」；「事件ID」+「错误码」且两者后面都跟着实际取值）。
//      这条约束的存在理由：帮助文档/产品手册类 200 页面满屏「防火墙 / WAF / 拦截」，
//      单词命中会把整个文档站误判成拦截页（单测显式覆盖该反例）。
//   3) 处置语义只认**完成时**句式（「已被…拦截」/「has been blocked」），
//      刻意不收「会被拦截 / 将拦截 / 拦截规则怎么配」这类讲解式现在时——文档里全是后者。
//   4) 置信度恒 ≤ GENERIC_CONFIDENCE_CAP（0.6），低于 WafIdentifier.WAF_HIGH_CONFIDENCE（0.8）
//      → 通用命中只用于「提示 + 发包形态建议（blockPolicy）」，永不触发 autoRetry 整站重跑。
//   5) 成对特征用 `^` + 双前瞻实现：既保证「同一响应里 A 与 B 都出现」，又让引擎只在 0 号位
//      试一次（非锚定的 (?=[\s\S]*A) 在长正文上会退化成 O(n²)）；正文另做长度截断。
//   6) 正则一律不带 /g：detectGenericBlock 是纯函数，lastIndex 状态会污染跨调用结果。
//
// 零依赖、纯函数、零额外发包：只做字符串匹配，不触碰网络与配置。

// 拦截语义状态码集合（429/503 同时是容量信号，退避交由 blockPolicy 处理）
export const GENERIC_BLOCK_STATUSES = new Set([403, 406, 418, 429, 503]);

// 限流/过载状态码（blockPolicy 仅在此集合内读取 Retry-After）
export const RATE_LIMIT_STATUSES = new Set([429, 503]);

// 通用拦截页候选的 vendor 标记（区别于 62 家厂商名：调用方据此知道「只确认被拦、不知被谁拦」）
export const GENERIC_BLOCK_VENDOR = 'generic_block';

// 置信度：单特征 0.55，多特征交叉每 +1 命中加 0.05，封顶 0.6。
// 封顶刻意压在 WAF_HIGH_CONFIDENCE(0.8) 之下——通用签名不足以支撑「整站套 tamper 重跑」这类放大流量的决策。
const CONFIDENCE_BASE = 0.55;
const CONFIDENCE_STEP = 0.05;
export const GENERIC_CONFIDENCE_CAP = 0.6;

// 参与匹配的文本上限（拦截文案集中在 <title>/首屏，超长正文没必要整篇扫）
const HAYSTACK_CAP = 200_000;

// 处置语义（强特征里的「已被处置」半边）：只认完成时，且限定在请求/访问/IP 主语上。
const DISPOSITION = String.raw`已被[\s\S]{0,16}(?:拦截|阻断|拒绝|封禁)|您的?(?:请求|访问|ip address)[^.\n<]{0,24}(?:has been|was) (?:blocked|denied|refused)`;

/**
 * 成对强特征：a 与 b 必须在同一段文本里同时出现（锚定 0 号位的双前瞻，单次线性扫描）。
 * @param {string} a 拦截语义子模式
 * @param {string} b 处置语义子模式
 * @returns {RegExp}
 */
const pair = (a, b) => new RegExp(`^(?=[\\s\\S]*(?:${a}))(?=[\\s\\S]*(?:${b}))`, 'i');

/**
 * 单特征强签名：本身即无歧义的拦截页标记（不是「提到拦截」，而是「拦截页才会输出」）。
 * @param {string} src
 * @returns {RegExp}
 */
const solo = (src) => new RegExp(`^(?=[\\s\\S]*(?:${src}))`, 'i');

/**
 * 强特征表：status === 200 时**只认这一层**（每条要么本身唯一无歧义，要么已成对）。
 * 每条 { id, sig, hint, family }：
 *   id     —— 稳定标识，进 evidence / alsoMatched，便于审计与按 id 统计命中率
 *   sig    —— RegExp（无 /g）
 *   hint   —— 给人看的判据说明（前端提示、报告注释复用）
 *   family —— 归类，供 blockPolicy / 报告按类决策，不参与匹配
 */
export const GENERIC_BLOCK_SIGS = [
  {
    id: 'gb-cn-attack-blocked',
    sig: pair(String.raw`含有攻击特征`, DISPOSITION),
    hint: '国内云 WAF 拦截页成对文案：判定含攻击特征 + 已被拦截',
    family: 'cn_waf',
  },
  {
    id: 'gb-cn-receipt-ids',
    // 要求标签后紧跟实际取值（事件ID: 0a1b2c…、错误码 403）；
    // 否则「根据事件ID和错误码查询防护规则」这种文档措辞会误命中。
    sig: pair(
      String.raw`事件\s*ID\s*[：:]?\s*[^.\n<]{0,12}[0-9a-zA-Z-]{6,}`,
      String.raw`错误码\s*[：:]?\s*[^.\n<]{0,12}\d{2,}`,
    ),
    hint: '拦截回执成对给出「事件ID」与「错误码」取值（云 WAF 工单式回执）',
    family: 'cn_waf',
  },
  {
    id: 'gb-block-disposition',
    sig: solo(DISPOSITION),
    hint: '响应正文以完成时自述本次请求已被拦截/阻断/拒绝',
    family: 'generic',
  },
  {
    id: 'gb-modsec-action',
    sig: /\bModSecurity Action\b|ModSecurity:\s*Access denied|This error was generated by (?:ModSecurity|mod_security)/i,
    hint: 'ModSecurity/Apache 默认拒绝页（ModSecurity Action 或 generated by ModSecurity）',
    family: 'oss_rule_engine',
  },
  {
    id: 'gb-cloudflare-block',
    sig: /cf-banner-inner|Attention Required!\s*(?:::|\|)/i,
    hint: 'Cloudflare 拦截页（cf-banner-inner 节点或 Attention Required! 标题）',
    family: 'cdn',
  },
  {
    id: 'gb-safedog-block',
    sig: pair(String.raw`安全狗`, DISPOSITION),
    hint: '安全狗拦截页（厂商名 + 处置句式成对）',
    family: 'cn_waf',
  },
  {
    id: 'gb-yunsuo-block',
    // yunsuo_session_verify 是云锁 JS 人机校验的 cookie/变量名：出现即说明响应正在下发验证挑战
    // （200 形态的隐形拦截）。文档不会把内部变量名当作正文输出，故允许单特征命中。
    sig: /yunsuo_session_verify|yunsuo_session_value/i,
    hint: '云锁 JS 人机校验（yunsuo_session_verify，200 形态验证页）',
    family: 'cn_waf',
  },
  {
    id: 'gb-safeline-block',
    sig: pair(String.raw`(?:SafeLine|雷池|长亭)`, String.raw`(?:${DISPOSITION}|安全检测|拦截说明)`),
    hint: '长亭雷池 SafeLine 拦截页（厂商名 + 处置文案成对）',
    family: 'cn_waf',
  },
  {
    id: 'gb-aliyun-waf-block',
    // waf_block.html 是阿里云 WAF 拦截页固定引用的图片资源名（页面结构特征，单特征即可定性）
    sig: /waf_block\.html/i,
    hint: '阿里云 WAF 拦截页（waf_block.html 资源引用）',
    family: 'cloud_waf',
  },
  {
    id: 'gb-aws-blocked-page',
    // 只有 "Request blocked" 一句太容易和文档/错误码表撞车，故与 CloudFront/AWS 错误页固定标题成对；
    // 纯 "403 + Request blocked" 的简拦页面仍会被第二层通用特征（gs-en-deny-word）接住。
    sig: pair(String.raw`\bRequest blocked\b`, String.raw`(?:403 ERROR|the request could not be satisfied)`),
    hint: 'AWS WAF / CloudFront 默认拦截页（Request blocked + 403 ERROR 标题成对）',
    family: 'cloud_waf',
  },
  {
    id: 'gb-cloud-block-phrase',
    sig: /blocked by (?:aws waf|aliyun waf|cloudflare|akamai|imperva|incapsula|yundun|qcloud|huaweicloud)/i,
    hint: '云 WAF 拦截页固定短句（"blocked by <厂商>"）',
    family: 'cloud_waf',
  },
];

/**
 * 通用特征表（第二层）：**只在** status ∈ GENERIC_BLOCK_STATUSES 时计入。
 * 这些词单独出现在 200 页面上毫无意义（产品文档、错误码表、控制台都会写「拦截」），
 * 所以它们被隔离在第二层，绝不参与 200 判定。
 */
export const GENERIC_SOFT_SIGS = [
  {
    id: 'gs-en-deny-word',
    sig: /\b(?:access denied|forbidden|not acceptable|no permission|request (?:rejected|refused)|unauthorized|blocked|denied)\b/i,
    hint: '英文拒绝文案（403/406 常见）',
    family: 'generic',
  },
  {
    id: 'gs-cn-deny-word',
    sig: /拦截|阻断|拒绝访问|禁止访问|访问受限|无权限|安全策略|防火墙|应用防护/i,
    hint: '中文拒绝文案或防护设备自述',
    family: 'cn_waf',
  },
  {
    id: 'gs-waf-marker',
    sig: /\bwaf\b|web application firewall|应用防火墙/i,
    hint: '响应自述经过 WAF 处理（配合拦截状态码才有意义）',
    family: 'generic',
  },
  {
    id: 'gs-rate-limit',
    sig: /rate.?limit|too many requests|请求过于频繁|访问频率|限流|超出配额/i,
    hint: '频率限制/配额提示（429/503 主要形态）',
    family: 'rate_limit',
  },
  {
    id: 'gs-receipt-marker',
    sig: /(?:incident|event|trace|request)[ _-]?(?:id|no\.?|编号)|错误码|工单|联系管理员/i,
    hint: '拦截页惯带的回执编号 / 报障指引',
    family: 'generic',
  },
];

// 参与匹配的响应头白名单：这几个头常直接暴露拦截或人机校验语义（如 set-cookie 里的校验 cookie 名）。
// 刻意不做「全量头部拼接」——x-request-id / x-powered-by 之类正常头会把通用匹配的区分度稀释掉。
const HEADER_KEYS = new Set(['server', 'via', 'set-cookie', 'refresh', 'location']);
// 另收特征性命名的拦截相关头（x-powered-by-safedog、x-waf-message、x-block-id …）
const HEADER_KEY_HINTS = /waf|safedog|yunsuo|block|shield|deny|firewall/i;

// 归一化匹配文本：白名单头值 + 正文，截断到 HAYSTACK_CAP
function buildHaystack(res) {
  const headers = res?.headers;
  let head = '';
  if (headers && typeof headers === 'object') {
    for (const [k, v] of Object.entries(headers)) {
      const key = String(k).toLowerCase();
      if (!HEADER_KEYS.has(key) && !HEADER_KEY_HINTS.test(key)) continue;
      if (v == null) continue;
      head += `${key}: ${Array.isArray(v) ? v.join(', ') : String(v)}\n`;
    }
  }
  const body = String(res?.body ?? res?.data ?? '');
  const text = head + body;
  return text.length > HAYSTACK_CAP ? text.slice(0, HAYSTACK_CAP) : text;
}

/**
 * 判定一个响应是否为「通用拦截页」（纯函数，零副作用、零发包）。
 *
 * @param {{status:number, headers?:object, body?:string}} res 指纹阶段已抓取的基线响应（或任意响应）
 * @returns {{id:string, vendor:'generic_block', confidence:number, evidence:string, hint:string, family:string, matchedIds:string[], status:number}|null}
 *          命中返回候选（confidence 恒 ≤ 0.6），未命中返回 null
 */
export function detectGenericBlock(res) {
  const status = Number(res?.status);
  if (!Number.isFinite(status)) return null; // 无状态码（网络失败 / direct 模式）不判定
  const isBlockStatus = GENERIC_BLOCK_STATUSES.has(status);
  // 只在两种情形下下判断：拦截状态码（可接受弱特征）、200（必须强特征）。其余一律 null。
  if (!isBlockStatus && status !== 200) return null;

  const text = buildHaystack(res);
  if (!text) return null;

  const strongHits = GENERIC_BLOCK_SIGS.filter((s) => s.sig.test(text));
  // 拦截状态码下仍要求「有文案」：裸 403（目录禁止访问、业务鉴权失败）不代表 WAF 拦截，
  // 此时改发包形态毫无意义，只会白白放大流量。
  const softHits = isBlockStatus ? GENERIC_SOFT_SIGS.filter((s) => s.sig.test(text)) : [];
  const hits = strongHits.concat(softHits);
  if (hits.length === 0) return null;

  // 主证据取首个强特征（hint/family 更能说明「被什么形态的拦截页挡住」），无强特征才退到弱特征
  const primary = hits[0];
  const matchedIds = hits.map((s) => s.id);
  const confidence = Math.min(GENERIC_CONFIDENCE_CAP, CONFIDENCE_BASE + (hits.length - 1) * CONFIDENCE_STEP);
  return {
    id: primary.id,
    vendor: GENERIC_BLOCK_VENDOR,
    confidence,
    // evidence 同时写明 status 与命中的特征 id：拦截结论必须可复核（哪个码 + 哪几条特征）
    evidence: `status=${status}; generic_block: ${matchedIds.join(', ')}`,
    hint: primary.hint,
    family: primary.family,
    matchedIds,
    status,
  };
}

export default detectGenericBlock;
