// 通用拦截页识别（blockSignatures）+ 置信度封顶 + 拦截策略（blockPolicy）测试。
// 关注点：① 真实形态拦截页必须命中（国产 WAF / OSS 引擎 / CDN / 云 WAF 各 1 条）；
//        ② 帮助文档类 200 页面绝不命中（这是保守判据的存在理由）；
//        ③ 置信度封顶 0.6 → 永不越过 autoRetry 的 0.8 门控（防误判放大流量）；
//        ④ WafIdentifier 接入顺序（厂商优先，通用作 alsoMatched 附注）与 'unknown' 一票否决；
//        ⑤ decideBlockPolicy 三分支 + Retry-After 两种格式。
import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  GENERIC_BLOCK_SIGS,
  GENERIC_SOFT_SIGS,
  detectGenericBlock,
  GENERIC_BLOCK_STATUSES,
  GENERIC_BLOCK_VENDOR,
  GENERIC_CONFIDENCE_CAP,
} from '../src/core/waf/blockSignatures.js';
import { WafIdentifier, WAF_HIGH_CONFIDENCE } from '../src/core/waf/WafIdentifier.js';
import { decideBlockPolicy, parseRetryAfter, isUntrustedVendor, MAX_BACKOFF_MS } from '../src/core/waf/blockPolicy.js';
import { WAF_RECOMMEND_MAP } from '../src/core/waf/wafRecommend.js';

// ── 0) 特征表自检 ─────────────────────────────────────────────────────────────
test('通用拦截页特征表：字段完整 + 正则无 /g（纯函数不受 lastIndex 污染）', () => {
  assert.ok(GENERIC_BLOCK_SIGS.length >= 8, '强特征表至少 8 条');
  assert.ok(GENERIC_SOFT_SIGS.length >= 4, '通用特征表至少 4 条');
  for (const s of [...GENERIC_BLOCK_SIGS, ...GENERIC_SOFT_SIGS]) {
    assert.equal(typeof s.id, 'string', `${s.id || '?'} 缺 id`);
    assert.equal(typeof s.hint, 'string', `${s.id} 缺 hint`);
    assert.equal(typeof s.family, 'string', `${s.id} 缺 family`);
    assert.ok(s.sig instanceof RegExp, `${s.id} 的 sig 必须是 RegExp`);
    assert.equal(s.sig.global, false, `${s.id} 的 sig 不能带 /g`);
    assert.ok(!s.sig.sticky, `${s.id} 的 sig 不能带 /y`);
  }
  const ids = new Set([...GENERIC_BLOCK_SIGS, ...GENERIC_SOFT_SIGS].map((s) => s.id));
  assert.equal(ids.size, GENERIC_BLOCK_SIGS.length + GENERIC_SOFT_SIGS.length, '特征 id 必须唯一');
});

test('拦截状态码集合覆盖 403/406/418/429/503', () => {
  for (const st of [403, 406, 418, 429, 503]) assert.ok(GENERIC_BLOCK_STATUSES.has(st), `应包含 ${st}`);
  assert.equal(GENERIC_BLOCK_STATUSES.has(500), false, '500 语义混杂，不作为拦截状态码');
  assert.equal(GENERIC_BLOCK_STATUSES.has(302), false, '302 不作为拦截状态码');
});

// ── 1) 真实形态拦截样本：各厂商 1 条，全部必须命中 ─────────────────────────────
const BLOCK_SAMPLES = [
  {
    name: '安全狗（403 拦截页）',
    res: {
      status: 403,
      headers: { server: 'nginx' },
      body: '<html><head><title>403 Forbidden</title></head><body><div class="block-page">'
        + '<h1>您的请求含有攻击特征，已被网站安全狗拦截</h1>'
        + '<p>事件ID：0a1b2c3d4e5f6a7b 错误码：403</p><p>如需恢复访问请联系管理员并附带以上编号</p>'
        + '</div></body></html>',
    },
    expectId: 'gb-cn-attack-blocked',
  },
  {
    name: '云锁（200 JS 人机校验页）',
    res: {
      status: 200,
      headers: { server: 'nginx', 'set-cookie': 'yunsuo_session_verify=9F8E7D6C5B4A3210; path=/; HttpOnly' },
      body: '<html><body><script>document.cookie="yunsuo_session_verify=9F8E7D6C5B4A3210;path=/";setTimeout(function(){location.reload();},1000);</script></body></html>',
    },
    expectId: 'gb-yunsuo-block',
  },
  {
    name: 'ModSecurity（406 默认拒绝页）',
    res: {
      status: 406,
      headers: {},
      body: '<html><head><title>406 Not Acceptable</title></head><body><h1>Not Acceptable!</h1>'
        + '<p>An appropriate representation of the requested resource could not be found on this server.</p>'
        + '<p>This error was generated by ModSecurity.</p><p>ModSecurity Action: deny</p></body></html>',
    },
    expectId: 'gb-modsec-action',
  },
  {
    name: 'Cloudflare（403 拦截页）',
    res: {
      status: 403,
      headers: { server: 'cloudflare', 'cf-ray': '8f3c1d2e4a5b6c7d-AMS' },
      body: '<!DOCTYPE html><html><head><title>Attention Required! | Cloudflare</title></head><body>'
        + '<div class="cf-wrapper"><div id="cf-banner-inner"><h1>Attention Required! | Cloudflare</h1>'
        + '<p>You</p></div></div></body></html>',
    },
    expectId: 'gb-cloudflare-block',
  },
  {
    name: '阿里云 WAF（403 拦截页）',
    res: {
      status: 403,
      headers: { server: 'Tengine' },
      body: '<html><head><title>403</title></head><body><div class="alicloud-terminal">'
        + '<img src="/_waf/static/waf_block.html" alt="blocked"/>'
        + '<p>您的请求含有攻击特征，已被网站管理员设置为拦截</p>'
        + '<p>事件ID: 0a1b2c3d4e5f6a7b8c9d0e1f 错误码 403</p></div></body></html>',
    },
    expectId: 'gb-aliyun-waf-block',
  },
  {
    name: '长亭雷池 SafeLine（403 拦截页）',
    res: {
      status: 403,
      headers: { server: 'nginx' },
      body: '<html><body><div id="block"><h1>请求已被安全引擎拦截</h1>'
        + '<p>blocked by SafeLine</p><p>拦截说明：您的请求存在恶意特征</p></div></body></html>',
    },
    expectId: 'gb-safeline-block',
  },
  {
    name: 'AWS WAF / CloudFront（403 Request blocked）',
    res: {
      status: 403,
      headers: { server: 'AkamaiGHost', 'x-amzn-requestid': 'b1c2d3e4-5555-6666-7777-888899990000' },
      body: '<HTML><HEAD><TITLE>ERROR: The request could not be satisfied</TITLE></HEAD><BODY>'
        + '<H1>403 ERROR</H1><H1>The request could not be satisfied.</H1><P>Request blocked</P></BODY></HTML>',
    },
    expectId: 'gb-aws-blocked-page',
  },
  {
    name: '自建网关限流（429 + 频率提示，走通用特征层）',
    res: {
      status: 429,
      headers: { 'retry-after': '15', server: 'openresty' },
      body: '<html><body><h1>Too Many Requests</h1><p>rate limit exceeded, please reduce your request frequency</p></body></html>',
    },
    expectId: undefined, // 弱特征命中即可，不锁定具体 id
  },
];

test('真实形态拦截页：安全狗/云锁/ModSecurity/Cloudflare/阿里云 WAF/雷池/AWS/限流 全部命中', () => {
  for (const { name, res, expectId } of BLOCK_SAMPLES) {
    const hit = detectGenericBlock(res);
    assert.ok(hit, `应命中：${name}`);
    assert.equal(hit.vendor, GENERIC_BLOCK_VENDOR, `${name} vendor 应为 generic_block`);
    if (expectId) assert.ok(hit.matchedIds.includes(expectId), `${name} 应命中 ${expectId}，实际 ${hit.matchedIds.join(',')}`);
    // evidence 必须自带可复核信息：状态码 + 命中特征 id
    assert.ok(hit.evidence.includes(`status=${res.status}`), `${name} evidence 应含 status`);
    assert.ok(/gb-|gs-/.test(hit.evidence), `${name} evidence 应含命中的特征 id`);
  }
});

test('置信度封顶：任何拦截样本都 ≤ 0.6 且低于 autoRetry 门控 0.8', () => {
  for (const { name, res } of BLOCK_SAMPLES) {
    const hit = detectGenericBlock(res);
    assert.ok(hit, `应命中：${name}`);
    assert.ok(hit.confidence <= GENERIC_CONFIDENCE_CAP, `${name} 置信度应 ≤ ${GENERIC_CONFIDENCE_CAP}，实际 ${hit.confidence}`);
    assert.ok(hit.confidence < WAF_HIGH_CONFIDENCE, `${name} 置信度必须低于 autoRetry 阈值`);
    assert.equal(typeof hit.hint, 'string');
    assert.equal(typeof hit.family, 'string');
  }
});

// ── 2) 反例：帮助文档类 200 页面绝不能命中（保守判据的核心目的）───────────────
const DOC_SAMPLES_200 = [
  {
    name: '云厂商 WAF 产品文档（提到 防火墙/WAF/拦截/403/攻击特征）',
    res: {
      status: 200,
      headers: { server: 'nginx', 'content-type': 'text/html' },
      body: '<html><head><title>什么是 Web 应用防火墙 · 产品文档</title></head><body>'
        + '<p>本文介绍如何开通 Web 应用防火墙（WAF）。开启防护规则后，恶意请求会被拦截并返回 403 状态码。</p>'
        + '<p>您可以在安全报告中查看事件 ID 与错误码，据此分析攻击特征。若需调整拦截策略，请在控制台配置白名单。</p>'
        + '</body></html>',
    },
  },
  {
    name: 'ModSecurity 手册（讲解 Action: deny 与拦截规则）',
    res: {
      status: 200,
      headers: { server: 'Apache' },
      body: '<html><body><h1>ModSecurity 规则手册</h1><p>ModSecurity 是一款开源 Web 应用防火墙（WAF）。'
        + '通过 SecRuleEngine 可以开启拦截；命中规则时可配置 Action 为 deny 以拒绝请求，返回 403。</p></body></html>',
    },
  },
  {
    name: '安全狗/云锁产品介绍页（厂商名 + 拦截字样）',
    res: {
      status: 200,
      headers: { server: 'nginx' },
      body: '<html><body><h1>服务器安全加固套件</h1><p>安全狗与云锁均支持自定义拦截规则、CC 防护与防火墙策略，'
        + '开启后异常访问将被阻断，可在控制台查看拦截日志。</p></body></html>',
    },
  },
  {
    name: '自建 WAF 接入指南（含错误码表 Request blocked 说明）',
    res: {
      status: 200,
      headers: { server: 'nginx' },
      body: '<html><body><h1>接入指南</h1><table><tr><td>403</td><td>Request blocked by WAF</td><td>请求被拦截</td></tr>'
        + '<tr><td>429</td><td>Too Many Requests</td><td>访问频率超限</td></tr></table></body></html>',
    },
  },
];

test('200 帮助文档/产品页：提到「防火墙 / WAF / 拦截」一律 0 命中', () => {
  for (const { name, res } of DOC_SAMPLES_200) {
    const hit = detectGenericBlock(res);
    assert.equal(hit, null, `不应命中：${name}${hit ? `（实际命中 ${hit.matchedIds.join(',')}）` : ''}`);
  }
});

test('拦截状态码但无任何拦截文案 → 0 命中（裸 403 不代表 WAF 拦截）', () => {
  assert.equal(detectGenericBlock({ status: 403, headers: { server: 'nginx' }, body: '' }), null);
  assert.equal(detectGenericBlock({ status: 403, headers: {}, body: '<html><body>Nothing here</body></html>' }), null);
  assert.equal(detectGenericBlock({ status: 429, headers: {}, body: 'slow down' }), null);
});

test('非拦截状态码（500/302/404）即使正文写了「已被拦截」也不判定', () => {
  for (const status of [500, 302, 404, 400]) {
    const hit = detectGenericBlock({ status, headers: {}, body: '<p>您的请求已被安全狗拦截</p>' });
    assert.equal(hit, null, `${status} 语义混杂，不应由通用层下结论`);
  }
});

test('空输入 / 无状态码 → null（direct 模式与网络失败不判定）', () => {
  assert.equal(detectGenericBlock(), null);
  assert.equal(detectGenericBlock({}), null);
  assert.equal(detectGenericBlock({ status: 'abc', body: 'blocked' }), null);
});

// ── 3) WafIdentifier 接入：厂商优先 / 通用兜底 / unknown 降级 ─────────────────
const wafId = new WafIdentifier();

test('WafIdentifier：无厂商签名但命中通用拦截页 → 返回 generic_block 候选（低置信）', () => {
  const resp = {
    status: 403,
    headers: { server: 'nginx' },
    body: '<html><body><h1>403</h1><p>您的请求含有攻击特征，已被本站安全防护拦截</p><p>事件ID：1234567890abcdef 错误码：403</p></body></html>',
  };
  const r = wafId.identify(resp);
  const g = r.find((c) => c.vendor === GENERIC_BLOCK_VENDOR);
  assert.ok(g, '应返回 generic_block 候选');
  assert.equal(r.length, 1, '未命中厂商签名时只应有通用候选');
  assert.equal(g.source, 'generic_block');
  assert.ok(g.confidence <= GENERIC_CONFIDENCE_CAP, '通用候选置信度必须封顶');
  assert.ok(g.evidence.includes('status=403'), 'evidence 应写明 status');
  assert.ok(g.evidence.includes('gb-'), 'evidence 应写明命中的特征 id');
  // 关键护栏：通用命中绝不触发自动 tamper 重跑（不放大流量）
  assert.equal(wafId.shouldAutoRetry(r, { wafEvasion: { autoRetry: true } }), false, '低置信通用命中不得触发 autoRetry');
});

test('WafIdentifier：同时命中厂商与通用签名 → 厂商优先，通用只作 alsoMatched 附注', () => {
  const resp = {
    status: 403,
    headers: { server: 'cloudflare', 'cf-ray': '8f3c1d2e4a5b6c7d-AMS' },
    body: '<html><head><title>Attention Required! | Cloudflare</title></head><body><div id="cf-banner-inner">Sorry, you have been blocked</div></body></html>',
  };
  const r = wafId.identify(resp);
  assert.equal(r.length, 1, '厂商优先：不新增 generic_block 候选条目');
  assert.equal(r[0].vendor, 'Cloudflare');
  assert.ok(r[0].confidence >= WAF_HIGH_CONFIDENCE, '厂商签名命中仍是高置信');
  assert.ok(Array.isArray(r[0].alsoMatched) && r[0].alsoMatched.includes('gb-cloudflare-block'), '通用命中应记入 alsoMatched');
});

test('WafIdentifier：干净 200 响应仍返回 []（零误报回归）', () => {
  assert.deepEqual(wafId.identify({ status: 200, headers: { server: 'nginx' }, body: '<html><body>hello</body></html>' }), []);
  assert.deepEqual(wafId.identify({}), []);
});

test('unknown 兜底：保留 0.5 但标注 source:none（无签名证据），行为结论不得越 0.8 门控', async () => {
  // 良性请求 200 长正文，触发请求 200 短正文：无拦截状态码、无拦截文案 → 只剩行为线索
  const httpClient = {
    request: async ({ url }) => {
      const id = new URL(url).searchParams.get('id');
      if (id === '1') return { status: 200, headers: {}, data: 'x'.repeat(4000) };
      return { status: 200, headers: {}, data: 'tiny' };
    },
  };
  const r = await wafId.activeProbe({ baseUrl: 'http://target.local/' }, httpClient);
  assert.equal(r.detected, true, '行为差异显著应标记疑似 WAF');
  assert.equal(r.vendor, null, '无厂商可命名');
  // 置信度维持既有值 0.5：autoRetry 门控本就要求 >= 0.8，0.5 不会触发重跑，无需降值
  assert.equal(r.confidence, 0.5, '行为兜底置信度保持既有语义（降值无收益）');
  assert.equal(r.source, 'none', '应显式标注零签名证据');
  assert.ok(r.confidence < WAF_HIGH_CONFIDENCE, '必须低于 autoRetry 阈值');
  // 真正的防护在下游：调用侧把 vendor 补成 'unknown' 后，blockPolicy 必须否决形态变更
  const p = decideBlockPolicy({ namedVendor: r.vendor || 'unknown', status: 200, headers: {}, config: {} });
  assert.equal(p.action, 'none', "vendor='unknown' 不得递出 preferTamper");
  assert.deepEqual(p.tamperHint, [], '也不得递出 _default 推荐链');
});

// ── 4) blockPolicy：三分支 + Retry-After 两种格式 ─────────────────────────────
const GENERIC_HIT = {
  id: 'gb-cn-attack-blocked',
  vendor: GENERIC_BLOCK_VENDOR,
  confidence: 0.55,
  evidence: 'status=403; generic_block: gb-cn-attack-blocked',
  hint: '国内云 WAF 拦截页成对文案',
  family: 'cn_waf',
  matchedIds: ['gb-cn-attack-blocked'],
  status: 403,
};

test('decideBlockPolicy：vendor=\'unknown\' 一票否决 → 只给 none（不递 tamper 建议）', () => {
  // 这是真正的流量放大风险入口：主动探测无厂商 → 调用侧写成 'unknown' → 若给 preferTamper
  // 就会拿 wafRecommend 的 _default 链重跑全站未命中点。
  const p = decideBlockPolicy({ genericBlock: GENERIC_HIT, namedVendor: 'unknown', status: 403, headers: {}, config: {} });
  assert.equal(p.action, 'none');
  assert.deepEqual(p.tamperHint, []);
  assert.equal(p.backoffMs, null);
  assert.ok(p.reason.includes('unknown'), 'reason 应说明否决原因');
  // 对象形式 + 大小写不敏感同样否决；且否决优先于 pause（即使有合法 Retry-After 也不改动作）
  const p2 = decideBlockPolicy({ genericBlock: null, namedVendor: { vendor: 'UNKNOWN' }, status: 429, headers: { 'retry-after': '5' }, config: {} });
  assert.equal(p2.action, 'none');
  assert.equal(p2.backoffMs, null, 'unknown 下不由本策略下发退避（容量退避与识别无关，由调用方用 parseRetryAfter 自理）');
  assert.ok(p2.reason.includes('Retry-After'), 'reason 应说明已忽略的 Retry-After，避免误以为数据丢失');
  // 判定函数本身：未给 vendor / 已命名厂商 / generic_block 均不属否决集
  assert.equal(isUntrustedVendor('unknown'), true);
  assert.equal(isUntrustedVendor({ vendor: 'unknown WAF' }), true);
  assert.equal(isUntrustedVendor(null), false);
  assert.equal(isUntrustedVendor('Cloudflare'), false);
  assert.equal(isUntrustedVendor({ vendor: GENERIC_BLOCK_VENDOR }), false);
});

test('decideBlockPolicy：命中 generic_block 且未配置 tamper → preferTamper + 推荐链', () => {
  const p = decideBlockPolicy({ genericBlock: GENERIC_HIT, status: 403, headers: {}, config: {} });
  assert.equal(p.action, 'preferTamper');
  assert.equal(p.backoffMs, null);
  // generic_block 已有专属推荐链（关键词级黑名单：算子替换优先，2026-09-10 实测）
  assert.deepEqual(p.tamperHint, [...WAF_RECOMMEND_MAP.generic_block]);
  assert.ok(p.tamperHint.length > 0 && typeof p.reason === 'string');
});

test('decideBlockPolicy：已识别厂商时推荐链取该厂商映射（generic 只作附注）', () => {
  const p = decideBlockPolicy({ genericBlock: GENERIC_HIT, namedVendor: { vendor: 'Cloudflare', confidence: 0.9 }, status: 403, headers: {}, config: {} });
  assert.equal(p.action, 'preferTamper');
  assert.deepEqual(p.tamperHint, [...WAF_RECOMMEND_MAP.Cloudflare]);
  assert.ok(p.reason.includes('Cloudflare'));
});

test('decideBlockPolicy：用户已显式配置 tamper → none（不覆盖人工接管）', () => {
  const p = decideBlockPolicy({
    genericBlock: GENERIC_HIT,
    status: 403,
    headers: {},
    config: { wafEvasion: { tamper: { enabled: true, plugins: ['between'] } } },
  });
  assert.equal(p.action, 'none');
  assert.deepEqual(p.tamperHint, []);
  assert.equal(p.backoffMs, null);
});

test('decideBlockPolicy：429/503 + Retry-After（秒数格式）→ pause + backoffMs', () => {
  const p = decideBlockPolicy({ genericBlock: null, status: 429, headers: { 'Retry-After': '12' }, config: {} });
  assert.equal(p.action, 'pause');
  assert.equal(p.backoffMs, 12000);
  assert.deepEqual(p.tamperHint, []);
  // 小数秒同样支持
  assert.equal(parseRetryAfter('0.5'), 500);
});

test('decideBlockPolicy：429 + Retry-After（HTTP-date 格式）→ pause，超上限截断 30s', () => {
  const soon = new Date(Date.now() + 5000).toUTCString();
  const p = decideBlockPolicy({ genericBlock: null, status: 503, headers: { 'retry-after': soon }, config: {} });
  assert.equal(p.action, 'pause');
  assert.ok(p.backoffMs > 3000 && p.backoffMs <= 5200, `HTTP-date 应换算为剩余毫秒，实际 ${p.backoffMs}`);
  // 超长 Retry-After 截断到上限，避免整轮扫描被冻住
  const far = new Date(Date.now() + 3600_000).toUTCString();
  const p2 = decideBlockPolicy({ genericBlock: null, status: 503, headers: { 'retry-after': far }, config: {} });
  assert.equal(p2.backoffMs, MAX_BACKOFF_MS);
  assert.equal(parseRetryAfter('999999'), MAX_BACKOFF_MS, '秒数格式同样受 30s 上限约束');
});

test('decideBlockPolicy：Retry-After 非法/缺失 → 忽略（不臆造退避时长）', () => {
  const bad = decideBlockPolicy({ genericBlock: null, status: 429, headers: { 'retry-after': 'soon-ish' }, config: {} });
  assert.equal(bad.action, 'none');
  assert.equal(bad.backoffMs, null);
  const missing = decideBlockPolicy({ genericBlock: null, status: 429, headers: {}, config: {} });
  assert.equal(missing.action, 'none');
  assert.equal(parseRetryAfter('soon-ish'), null);
  assert.equal(parseRetryAfter(undefined), null);
  assert.equal(parseRetryAfter(''), null);
  // 已过期的 HTTP-date：视为「无需等待」而不是忽略，交由调用方立即恢复
  assert.equal(parseRetryAfter(new Date(Date.now() - 60_000).toUTCString()), 0);
});

test('decideBlockPolicy：限流优先于换形态，但推荐链仍作为退避后的建议保留', () => {
  const p = decideBlockPolicy({ genericBlock: { ...GENERIC_HIT, status: 429, family: 'rate_limit' }, status: 429, headers: { 'retry-after': '5' }, config: {} });
  assert.equal(p.action, 'pause', '429 是容量信号：先降速再谈绕过');
  assert.equal(p.backoffMs, 5000);
  assert.deepEqual(p.tamperHint, [...WAF_RECOMMEND_MAP.generic_block], '退避后仍携带 tamper 建议');
});

test('decideBlockPolicy：无拦截证据 → none（保持当前发包形态）', () => {
  const p = decideBlockPolicy({ genericBlock: null, namedVendor: null, status: 200, headers: {}, config: {} });
  assert.equal(p.action, 'none');
  assert.deepEqual(p.tamperHint, []);
  assert.equal(p.backoffMs, null);
  assert.equal(typeof p.reason, 'string');
});

test('decideBlockPolicy：输出契约固定四字段（调用方可无条件消费）', () => {
  const cases = [
    { genericBlock: GENERIC_HIT, status: 403, headers: {}, config: {} },
    { genericBlock: null, status: 429, headers: { 'retry-after': '1' }, config: {} },
    {},
  ];
  for (const c of cases) {
    const p = decideBlockPolicy(c);
    assert.deepEqual(Object.keys(p).sort(), ['action', 'backoffMs', 'reason', 'tamperHint']);
    assert.ok(['none', 'preferTamper', 'pause'].includes(p.action));
    assert.ok(Array.isArray(p.tamperHint));
    assert.ok(p.backoffMs === null || (typeof p.backoffMs === 'number' && p.backoffMs >= 0 && p.backoffMs <= MAX_BACKOFF_MS));
  }
});
