// F-20 增量测试：WAF 指纹识别（WafIdentifier）+ 推荐（wafRecommend）
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { WafIdentifier } from '../src/core/waf/WafIdentifier.js';
import { recommend } from '../src/core/waf/wafRecommend.js';
import { WAF_RULES } from '../src/core/waf/wafRules.js';

test('识别 Cloudflare：cf-ray + Server: cloudflare', () => {
  const id = new WafIdentifier();
  const r = id.identify({ status: 200, headers: { 'cf-ray': 'abc', server: 'cloudflare' }, body: '' });
  const cf = r.find((c) => c.vendor === 'Cloudflare');
  assert.ok(cf, '应识别 Cloudflare');
  assert.ok(cf.confidence >= 0.8, '命中即 0.8+');
});

test('无 WAF 特征 → 返回 []（零误报）', () => {
  const id = new WafIdentifier();
  const r = id.identify({ status: 200, headers: { server: 'nginx' }, body: '<html>hello</html>' });
  assert.deepEqual(r, []);
});

test('识别 ModSecurity：默认拦截页 body 命中', () => {
  const id = new WafIdentifier();
  const r = id.identify({ status: 406, headers: {}, body: 'This error was generated by ModSecurity.' });
  const m = r.find((c) => c.vendor === 'ModSecurity');
  assert.ok(m, '应识别 ModSecurity');
});

test('header key 大小写不敏感', () => {
  const id = new WafIdentifier();
  const r = id.identify({ status: 200, headers: { 'CF-RAY': 'x', SERVER: 'CLOUDFLARE' }, body: '' });
  const cf = r.find((c) => c.vendor === 'Cloudflare');
  assert.ok(cf, '大写头也应命中');
});

test('多 matcher 命中 → confidence 升级（高于单命中）', () => {
  const id = new WafIdentifier();
  const one = id.identify({ status: 200, headers: { 'cf-ray': 'x' }, body: '' });
  const two = id.identify({ status: 200, headers: { 'cf-ray': 'x', server: 'cloudflare' }, body: '' });
  const oneC = one.find((c) => c.vendor === 'Cloudflare').confidence;
  const twoC = two.find((c) => c.vendor === 'Cloudflare').confidence;
  assert.ok(twoC > oneC, '多 matcher 命中应提升置信度');
});

test('聚合多个 vendor（Cloudflare + ModSecurity）', () => {
  const id = new WafIdentifier();
  const r = id.identify({ status: 406, headers: { 'cf-ray': 'x', server: 'cloudflare' }, body: 'modsecurity blocked' });
  const vendors = r.map((c) => c.vendor);
  assert.ok(vendors.includes('Cloudflare'), '应含 Cloudflare');
  assert.ok(vendors.includes('ModSecurity'), '应含 ModSecurity');
});

test('按 confidence 降序排序', () => {
  const id = new WafIdentifier();
  // 构造一个两命中（高置信）与一个单命中（低置信）
  const r = id.identify({ status: 501, headers: { 'cf-ray': 'x', server: 'cloudflare' }, body: 'modsecurity' });
  for (let i = 1; i < r.length; i++) {
    assert.ok(r[i - 1].confidence >= r[i].confidence);
  }
});

test('推荐映射：Cloudflare → 对应 plugins', () => {
  const sug = recommend([{ vendor: 'Cloudflare', confidence: 0.9, evidence: 'x' }]);
  assert.equal(sug.length, 1);
  // [P0-FIX] 差异化后 Cloudflare 推荐：space2comment, charencode, randomcase
  assert.deepEqual(sug[0].plugins, ['space2comment', 'charencode', 'randomcase']);
});

test('推荐映射：无命中 vendor 走 _default fallback（仍返回非空推荐）', () => {
  const sug = recommend([
    { vendor: 'UnknownVendor', confidence: 0.9, evidence: 'x' },
    { vendor: 'AWS_WAF', confidence: 0.9, evidence: 'x' },
  ]);
  // _default fallback 使 UnknownVendor 也返回非空推荐
  assert.equal(sug.length, 2);
  assert.ok(sug.some((s) => s.vendor === 'AWS_WAF'));
});

test('WAF_RULES 覆盖 60+ 类常见 WAF（WAF-v3 扩库 30→62）', () => {
  // 坑 B：扩库后原 ===7 断言必红，改为数量护栏 >= 60（允许 60–70）
  assert.ok(Object.keys(WAF_RULES).length >= 60, `当前 ${Object.keys(WAF_RULES).length} 条，应 >= 60`);
});
